import { MD5 } from ".core/md5.js";
import { SHA256 } from ".core/sha256.js";
import { cipher } from ".core/cipher.js";
import { handleHTML, handleHTMLSubmit } from ".core/html.js";
import { optimisecss, minifycss } from ".core/css.js";
import { optimisejs, minifyjs } from ".core/js.js";
import { handleLatex } from ".core/latex.js";
import { fetchUrlToCurrentNote, openFetchModal, handleFetchSubmit } from ".core/fetch.js";

window.MD5 = MD5;
window.SHA256 = SHA256;
window.cipher = cipher;
window.handleHTML = handleHTML;
window.handleHTMLSubmit = handleHTMLSubmit;
window.optimisecss = optimisecss;
window.minifycss = minifycss;
window.optimisejs = optimisejs;
window.minifyjs = minifyjs;
window.handleLatex = handleLatex;
window.fetchUrlToCurrentNote = fetchUrlToCurrentNote;
window.openFetchModal = openFetchModal;
window.handleFetchSubmit = handleFetchSubmit;
