import { MD5 } from "./code/md5.js";
import { SHA256 } from "./code/sha256.js";
import { cipher } from "./code/cipher.js";
import { handleHTML, handleHTMLSubmit } from "./code/html.js";
import { optimisecss, minifycss } from "./code/css.js";
import { optimisejs, minifyjs } from "./code/js.js";
import { handleLatex } from "./code/latex.js";
import { fetchUrlToCurrentNote, openFetchModal, handleFetchSubmit } from "./code/fetch.js";

window.MD5 = MD5;
window.SHA256 = SHA256;
window.cipher = cipher;
window.handleHTML = handleHTML;
window.handleHTMLSubmit = handleHTMLSubmit;
window.optimisecss = optimisecss;
window.minifycss = minifycss;
window.optimisejs = optimisejs;
window.minifyjs = minifyjs;
window.handleLatex = handleLatex;
window.fetchUrlToCurrentNote = fetchUrlToCurrentNote;
window.openFetchModal = openFetchModal;
window.handleFetchSubmit = handleFetchSubmit;
